/*
=========================================================
RENEWABLE ENERGY PERFORMANCE ANALYSIS
=========================================================

Project: Renewable Energy Analytics
Database: Renewable_Energy
Tool: PostgreSQL

Objective:
Analyze renewable energy generation, billing,
receivables, transmission losses and RKVAH losses
to identify plant-level and monthly performance.

Author: Nikita
=========================================================
*/


-- =====================================================
-- 1. DATA VALIDATION & EXPLORATION
-- =====================================================


-- Q1: Validate monthly generation record count

SELECT
    COUNT(*) AS total_records
FROM monthly_generation;


-- Q2: Check duplicate plant-month records

SELECT
    plant_id,
    month,
    COUNT(*) AS record_count
FROM monthly_generation
GROUP BY plant_id, month
HAVING COUNT(*) > 1;


-- Q3: Check missing values in monthly generation

SELECT
    COUNT(*) FILTER (WHERE plant_id IS NULL) AS null_plant_id,
    COUNT(*) FILTER (WHERE energy_generated_kwh IS NULL) AS null_generation,
    COUNT(*) FILTER (WHERE energy_exported_kwh IS NULL) AS null_export,
    COUNT(*) FILTER (WHERE import_units IS NULL) AS null_import_units
FROM monthly_generation;


-- Q4: Total energy generated by plant

SELECT
    plant_id,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_generated DESC;


-- Q5: Plant with highest total generation

SELECT
    plant_id,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_generated DESC
LIMIT 1;


-- Q6: Monthly energy generation

SELECT
    month,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY month
ORDER BY month;


-- Q7: Month with highest total generation

SELECT
    month,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY month
ORDER BY total_energy_generated DESC
LIMIT 1;


-- Q8: Generation vs export by plant and month

SELECT
    plant_id,
    month,
    SUM(energy_generated_kwh) AS total_energy_generated,
    SUM(energy_exported_kwh) AS total_energy_exported
FROM monthly_generation
GROUP BY plant_id, month;


-- Q9: Monthly export efficiency

SELECT
    plant_id,
    month,
    SUM(energy_generated_kwh) AS total_energy_generated,
    SUM(energy_exported_kwh) AS total_energy_exported,
    ROUND(
        SUM(energy_exported_kwh) /
        NULLIF(SUM(energy_generated_kwh), 0) * 100,
        2
    ) AS export_efficiency_pct
FROM monthly_generation
GROUP BY plant_id, month;


-- Q10: Plant with highest average export efficiency

SELECT
    plant_id,
    AVG(export_efficiency) AS avg_export_efficiency
FROM (
    SELECT
        plant_id,
        month,
        SUM(energy_exported_kwh) /
        NULLIF(SUM(energy_generated_kwh), 0) * 100
        AS export_efficiency
    FROM monthly_generation
    GROUP BY plant_id, month
) AS monthly_efficiency
GROUP BY plant_id
ORDER BY avg_export_efficiency DESC
LIMIT 1;



-- =====================================================
-- 2. GENERATION & PLANT PERFORMANCE
-- =====================================================


-- Q11: Total energy generation by financial year

SELECT
    financial_year,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY financial_year
ORDER BY financial_year;


-- Q12: Top-performing plant in each financial year

WITH ranked_plants AS (
    SELECT
        plant_id,
        financial_year,
        SUM(energy_generated_kwh) AS total_energy_generated,
        DENSE_RANK() OVER (
            PARTITION BY financial_year
            ORDER BY SUM(energy_generated_kwh) DESC
        ) AS generation_rank
    FROM monthly_generation
    GROUP BY plant_id, financial_year
)
SELECT
    plant_id,
    financial_year,
    total_energy_generated
FROM ranked_plants
WHERE generation_rank = 1
ORDER BY financial_year;


-- Q13: Classify plants based on total generation

WITH plant_generation AS (
    SELECT
        plant_id,
        SUM(energy_generated_kwh) AS total_energy_generated
    FROM monthly_generation
    GROUP BY plant_id
)
SELECT
    plant_id,
    total_energy_generated,
    CASE
        WHEN total_energy_generated > 5000000 THEN 'High'
        WHEN total_energy_generated >= 2000000 THEN 'Medium'
        ELSE 'Low'
    END AS performance_category
FROM plant_generation
ORDER BY total_energy_generated DESC;


-- Q14: Count plants in each performance category

WITH plant_generation AS (
    SELECT
        plant_id,
        SUM(energy_generated_kwh) AS total_energy_generated
    FROM monthly_generation
    GROUP BY plant_id
),
classified_plants AS (
    SELECT
        plant_id,
        total_energy_generated,
        CASE
            WHEN total_energy_generated > 5000000 THEN 'High'
            WHEN total_energy_generated >= 2000000 THEN 'Medium'
            ELSE 'Low'
        END AS performance_category
    FROM plant_generation
)
SELECT
    performance_category,
    COUNT(*) AS plant_count
FROM classified_plants
GROUP BY performance_category
ORDER BY plant_count DESC;


-- Q15: Average total generation per plant

SELECT
    AVG(total_energy_generated) AS avg_plant_generation
FROM (
    SELECT
        plant_id,
        SUM(energy_generated_kwh) AS total_energy_generated
    FROM monthly_generation
    GROUP BY plant_id
) AS plant_generation;


-- Q16: Highest monthly generation recorded by each plant

SELECT
    plant_id,
    MAX(energy_generated_kwh) AS highest_monthly_generation
FROM monthly_generation
GROUP BY plant_id
ORDER BY highest_monthly_generation DESC;


-- Q17: Lowest monthly generation recorded by each plant

SELECT
    plant_id,
    MIN(energy_generated_kwh) AS lowest_monthly_generation
FROM monthly_generation
GROUP BY plant_id
ORDER BY lowest_monthly_generation;


-- Q18: Average monthly generation by plant

SELECT
    plant_id,
    AVG(energy_generated_kwh) AS avg_monthly_generation
FROM monthly_generation
GROUP BY plant_id
ORDER BY avg_monthly_generation DESC;


-- Q19: Total energy exported by plant

SELECT
    plant_id,
    SUM(energy_exported_kwh) AS total_energy_exported
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_exported DESC;


-- Q20: Generation vs export by financial year

SELECT
    financial_year,
    SUM(energy_generated_kwh) AS total_energy_generated,
    SUM(energy_exported_kwh) AS total_energy_exported
FROM monthly_generation
GROUP BY financial_year
ORDER BY financial_year;



-- =====================================================
-- 3. EXPORT EFFICIENCY & PLANT CONTRIBUTION
-- =====================================================


-- Q21: Overall export efficiency

SELECT
    SUM(energy_generated_kwh) AS total_energy_generated,
    SUM(energy_exported_kwh) AS total_energy_exported,
    ROUND(
        SUM(energy_exported_kwh) /
        NULLIF(SUM(energy_generated_kwh), 0) * 100,
        2
    ) AS overall_export_efficiency_pct
FROM monthly_generation;


-- Q22: Monthly export efficiency

SELECT
    month,
    SUM(energy_generated_kwh) AS total_energy_generated,
    SUM(energy_exported_kwh) AS total_energy_exported,
    ROUND(
        SUM(energy_exported_kwh) /
        NULLIF(SUM(energy_generated_kwh), 0) * 100,
        2
    ) AS export_efficiency_pct
FROM monthly_generation
GROUP BY month
ORDER BY month;


-- Q23: Plant-wise export efficiency

SELECT
    plant_id,
    SUM(energy_generated_kwh) AS total_energy_generated,
    SUM(energy_exported_kwh) AS total_energy_exported,
    ROUND(
        SUM(energy_exported_kwh) /
        NULLIF(SUM(energy_generated_kwh), 0) * 100,
        2
    ) AS export_efficiency_pct
FROM monthly_generation
GROUP BY plant_id
ORDER BY export_efficiency_pct DESC;


-- Q24: Plant with highest total energy export

SELECT
    plant_id,
    SUM(energy_exported_kwh) AS total_energy_exported
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_exported DESC
LIMIT 1;


-- Q25: Plant with lowest total energy export

SELECT
    plant_id,
    SUM(energy_exported_kwh) AS total_energy_exported
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_exported
LIMIT 1;


-- Q26: Rank months based on total energy generation

SELECT
    month,
    SUM(energy_generated_kwh) AS total_energy_generated,
    DENSE_RANK() OVER (
        ORDER BY SUM(energy_generated_kwh) DESC
    ) AS generation_rank
FROM monthly_generation
GROUP BY month
ORDER BY generation_rank;


-- Q27: Top 3 plants by total energy generation

SELECT
    plant_id,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_generated DESC
LIMIT 3;


-- Q28: Bottom 3 plants by total energy generation

SELECT
    plant_id,
    SUM(energy_generated_kwh) AS total_energy_generated
FROM monthly_generation
GROUP BY plant_id
ORDER BY total_energy_generated
LIMIT 3;


-- Q29: Plant contribution to total energy generation

SELECT
    plant_id,
    SUM(energy_generated_kwh) AS plant_generation,
    SUM(SUM(energy_generated_kwh)) OVER () AS total_generation,
    ROUND(
        SUM(energy_generated_kwh) /
        NULLIF(SUM(SUM(energy_generated_kwh)) OVER (), 0) * 100,
        2
    ) AS generation_contribution_pct
FROM monthly_generation
GROUP BY plant_id
ORDER BY generation_contribution_pct DESC;


-- Q30: Plants contributing more than 5% of total generation

WITH plant_contribution AS (
    SELECT
        plant_id,
        SUM(energy_generated_kwh) AS plant_generation,
        SUM(SUM(energy_generated_kwh)) OVER () AS total_generation
    FROM monthly_generation
    GROUP BY plant_id
)
SELECT
    plant_id,
    plant_generation,
    ROUND(
        plant_generation /
        NULLIF(total_generation, 0) * 100,
        2
    ) AS generation_contribution_pct
FROM plant_contribution
WHERE plant_generation /
      NULLIF(total_generation, 0) * 100 > 5
ORDER BY generation_contribution_pct DESC;



-- =====================================================
-- 4. BILLING & RECEIVABLES ANALYSIS
-- =====================================================


-- Q31: Total invoice amount by financial year
-- Financial year is derived because the source financial_year
-- column is NULL in the billing table.

WITH billing_fy AS (
    SELECT
        CASE
            WHEN EXTRACT(
                MONTH FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
            ) >= 4
            THEN 'FY ' ||
                 EXTRACT(
                     YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                 ) ||
                 '-' ||
                 RIGHT(
                     (
                         EXTRACT(
                             YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                         ) + 1
                     )::text,
                     2
                 )
            ELSE 'FY ' ||
                 (
                     EXTRACT(
                         YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                     ) - 1
                 ) ||
                 '-' ||
                 RIGHT(
                     EXTRACT(
                         YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                     )::text,
                     2
                 )
        END AS derived_financial_year,
        invoice_amount
    FROM billing
)
SELECT
    derived_financial_year,
    SUM(invoice_amount) AS total_invoice_amount
FROM billing_fy
GROUP BY derived_financial_year
ORDER BY derived_financial_year;


-- Q32: Total billing amount by plant

SELECT
    plant_id,
    SUM(invoice_amount) AS total_invoice_amount
FROM billing
GROUP BY plant_id
ORDER BY total_invoice_amount DESC;


-- Q33: Total export units billed by plant

SELECT
    plant_id,
    SUM(export_units) AS total_export_units
FROM billing
GROUP BY plant_id
ORDER BY total_export_units DESC;


-- Q34: Average tariff per unit by plant

SELECT
    plant_id,
    AVG(tariff_per_unit) AS avg_tariff_per_unit
FROM billing
GROUP BY plant_id
ORDER BY avg_tariff_per_unit DESC;


-- Q35: Highest-value invoice

SELECT
    invoice_no,
    plant_id,
    billing_month,
    invoice_amount
FROM billing
ORDER BY invoice_amount DESC
LIMIT 1;


-- Q36: Lowest-value invoice

SELECT
    invoice_no,
    plant_id,
    billing_month,
    invoice_amount
FROM billing
ORDER BY invoice_amount
LIMIT 1;


-- Q37: Total TDS by financial year

WITH billing_fy AS (
    SELECT
        CASE
            WHEN EXTRACT(
                MONTH FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
            ) >= 4
            THEN 'FY ' ||
                 EXTRACT(
                     YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                 ) ||
                 '-' ||
                 RIGHT(
                     (
                         EXTRACT(
                             YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                         ) + 1
                     )::text,
                     2
                 )
            ELSE 'FY ' ||
                 (
                     EXTRACT(
                         YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                     ) - 1
                 ) ||
                 '-' ||
                 RIGHT(
                     EXTRACT(
                         YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                     )::text,
                     2
                 )
        END AS derived_financial_year,
        tds
    FROM billing
)
SELECT
    derived_financial_year,
    SUM(tds) AS total_tds
FROM billing_fy
GROUP BY derived_financial_year
ORDER BY derived_financial_year;


-- Q38: Total receivable amount by financial year

WITH billing_fy AS (
    SELECT
        CASE
            WHEN EXTRACT(
                MONTH FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
            ) >= 4
            THEN 'FY ' ||
                 EXTRACT(
                     YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                 ) ||
                 '-' ||
                 RIGHT(
                     (
                         EXTRACT(
                             YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                         ) + 1
                     )::text,
                     2
                 )
            ELSE 'FY ' ||
                 (
                     EXTRACT(
                         YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                     ) - 1
                 ) ||
                 '-' ||
                 RIGHT(
                     EXTRACT(
                         YEAR FROM TO_DATE('01-' || billing_month, 'DD-Mon-YY')
                     )::text,
                     2
                 )
        END AS derived_financial_year,
        amount_receivable
    FROM billing
)
SELECT
    derived_financial_year,
    SUM(amount_receivable) AS total_amount_receivable
FROM billing_fy
GROUP BY derived_financial_year
ORDER BY derived_financial_year;


-- Q39: Overall receivable percentage

SELECT
    SUM(invoice_amount) AS total_invoice_amount,
    SUM(amount_receivable) AS total_amount_receivable,
    ROUND(
        SUM(amount_receivable) /
        NULLIF(SUM(invoice_amount), 0) * 100,
        2
    ) AS receivable_percentage
FROM billing;


-- Q40: Total outstanding amount by plant

SELECT
    plant_id,
    SUM(invoice_amount) AS total_invoice_amount,
    SUM(amount_receivable) AS total_amount_receivable,
    SUM(invoice_amount - amount_receivable) AS total_outstanding
FROM billing
GROUP BY plant_id
ORDER BY total_outstanding DESC;


-- Q41: Monthly billing amount

SELECT
    billing_month,
    SUM(invoice_amount) AS total_invoice_amount
FROM billing
GROUP BY billing_month
ORDER BY billing_month;


-- Q42: Monthly receivable amount

SELECT
    billing_month,
    SUM(amount_receivable) AS total_amount_receivable
FROM billing
GROUP BY billing_month
ORDER BY billing_month;


-- Q43: Plant-wise receivable percentage

SELECT
    plant_id,
    SUM(invoice_amount) AS total_invoice_amount,
    SUM(amount_receivable) AS total_amount_receivable,
    ROUND(
        SUM(amount_receivable) /
        NULLIF(SUM(invoice_amount), 0) * 100,
        2
    ) AS receivable_percentage
FROM billing
GROUP BY plant_id
ORDER BY receivable_percentage DESC;


-- Q44: Total outstanding amount

SELECT
    SUM(invoice_amount) AS total_invoice_amount,
    SUM(amount_receivable) AS total_amount_receivable,
    SUM(invoice_amount - amount_receivable) AS total_outstanding
FROM billing;


-- Q45: Plant with highest outstanding amount

SELECT
    plant_id,
    SUM(invoice_amount - amount_receivable) AS total_outstanding
FROM billing
GROUP BY plant_id
ORDER BY total_outstanding DESC
LIMIT 1;


-- Q46: Billing contribution by plant

SELECT
    plant_id,
    SUM(invoice_amount) AS plant_invoice_amount,
    SUM(SUM(invoice_amount)) OVER () AS total_invoice_amount,
    ROUND(
        SUM(invoice_amount) /
        NULLIF(SUM(SUM(invoice_amount)) OVER (), 0) * 100,
        2
    ) AS billing_contribution_pct
FROM billing
GROUP BY plant_id
ORDER BY billing_contribution_pct DESC;


-- Q47: Plants contributing more than 5% of total billing

WITH plant_billing AS (
    SELECT
        plant_id,
        SUM(invoice_amount) AS plant_invoice_amount,
        SUM(SUM(invoice_amount)) OVER () AS total_invoice_amount
    FROM billing
    GROUP BY plant_id
)
SELECT
    plant_id,
    plant_invoice_amount,
    ROUND(
        plant_invoice_amount /
        NULLIF(total_invoice_amount, 0) * 100,
        2
    ) AS billing_contribution_pct
FROM plant_billing
WHERE plant_invoice_amount /
      NULLIF(total_invoice_amount, 0) * 100 > 5
ORDER BY billing_contribution_pct DESC;


-- Q48: Number of invoices generated by plant

SELECT
    plant_id,
    COUNT(invoice_no) AS invoice_count
FROM billing
GROUP BY plant_id
ORDER BY invoice_count DESC;


-- Q49: Average invoice value by plant

SELECT
    plant_id,
    AVG(invoice_amount) AS avg_invoice_amount
FROM billing
GROUP BY plant_id
ORDER BY avg_invoice_amount DESC;


-- Q50: Combine billing and generation performance by plant

WITH billing_summary AS (
    SELECT
        plant_id,
        SUM(invoice_amount) AS total_invoice_amount,
        SUM(amount_receivable) AS total_amount_receivable
    FROM billing
    GROUP BY plant_id
),
generation_summary AS (
    SELECT
        plant_id,
        SUM(energy_generated_kwh) AS total_energy_generated,
        SUM(energy_exported_kwh) AS total_energy_exported
    FROM monthly_generation
    GROUP BY plant_id
)
SELECT
    b.plant_id,
    b.total_invoice_amount,
    b.total_amount_receivable,
    g.total_energy_generated,
    g.total_energy_exported
FROM billing_summary b
JOIN generation_summary g
    ON b.plant_id = g.plant_id
ORDER BY b.plant_id;



-- =====================================================
-- 5. TRANSMISSION LOSS ANALYSIS
-- =====================================================


-- Q51: Average transmission loss percentage by plant

SELECT
    plant_id,
    AVG(tl_loss_percentage) AS avg_transmission_loss_pct
FROM transmission_loss
GROUP BY plant_id
ORDER BY avg_transmission_loss_pct DESC;


-- Q52: Monthly average transmission loss percentage

SELECT
    month,
    AVG(tl_loss_percentage) AS avg_transmission_loss_pct
FROM transmission_loss
GROUP BY month
ORDER BY month;


-- Q53: Plant with highest average transmission loss percentage

SELECT
    plant_id,
    AVG(tl_loss_percentage) AS avg_transmission_loss_pct
FROM transmission_loss
GROUP BY plant_id
ORDER BY avg_transmission_loss_pct DESC
LIMIT 1;


-- Q54: Total transmission loss units by plant

SELECT
    plant_id,
    SUM(tl_loss_units) AS total_transmission_loss_units
FROM transmission_loss
GROUP BY plant_id
ORDER BY total_transmission_loss_units DESC;


-- Q55: Highest individual transmission loss percentage

SELECT
    plant_id,
    month,
    tl_loss_percentage
FROM transmission_loss
ORDER BY tl_loss_percentage DESC
LIMIT 1;


-- Q56: Lowest individual transmission loss percentage

SELECT
    plant_id,
    month,
    tl_loss_percentage
FROM transmission_loss
ORDER BY tl_loss_percentage
LIMIT 1;


-- Q57: Month with highest total transmission loss units

SELECT
    month,
    SUM(tl_loss_units) AS total_transmission_loss_units
FROM transmission_loss
GROUP BY month
ORDER BY total_transmission_loss_units DESC
LIMIT 1;


-- Q58: Month with lowest total transmission loss units

SELECT
    month,
    SUM(tl_loss_units) AS total_transmission_loss_units
FROM transmission_loss
GROUP BY month
ORDER BY total_transmission_loss_units
LIMIT 1;


-- Q59: Plant with highest total transmission loss units

SELECT
    plant_id,
    SUM(tl_loss_units) AS total_transmission_loss_units
FROM transmission_loss
GROUP BY plant_id
ORDER BY total_transmission_loss_units DESC
LIMIT 1;


-- Q60: Average transmission loss percentage by financial year

SELECT
    financial_year,
    AVG(tl_loss_percentage) AS avg_transmission_loss_pct
FROM transmission_loss
GROUP BY financial_year
ORDER BY financial_year;
